# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #Services
    app.postservice:
        class: AppBundle\Service\PostService
        arguments: [ "@doctrine.orm.entity_manager", "@app.postrepository" ]

    #Repositories
    app.postrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\Post
